package dev.filipnikolov.vector.deployment.model;

public enum DeploymentEventType {
    DEPLOY_TRIGGERED,
    BUILD_STARTED,
    BUILD_FINISHED,
    DEPLOY_STARTED,
    DEPLOY_FINISHED,
    FAILED,
    CRASHED,
    RESTARTED,
    STOPPED,
    MANUAL_ROLLBACK,
    WEBHOOK_IGNORED,
    PIN_RELEASED,
    UPDATE_AVAILABLE,
    UPDATE_TRIGGERED,
    UPDATE_SUCCESS,
    UPDATE_FAILED,
    UPDATER_UNREACHABLE,
    SELF_APP_BOOTSTRAPPED,
    SUBDOMAIN_CHANGED
}
