server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/launchpad
spring.datasource.username=launchpad
spring.datasource.password=launchpad

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

github.webhook.secret=launchpad_secret

docker.socket=unix:///Users/filip/.orbstack/run/docker.sock
traefik.network=traefik
traefik.domain=localhost