name: Backend

on:
  push:
    branches: [dev]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: filipn123/launchpad-backend:latest

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: filipn123/launchpad-backend:latest